#! /bin/bash -l
#SBATCH -A b
#SBATCH -p core
#SBATCH -n 16
#SBATCH -J trini_nor_insilico_155
#SBATCH -t 3-00:00:00

module load bioinfo-tools
module load perl/5.24.0
module load trinity/2.1.0

cd /proj/b/nobackup/Pca/insilico_norPca

TRINITY_RNASEQ_ROOT/util/insilico_read_normalization.pl --seqType fq --JM 100G --max_cov 30 --left R1_001.fastq.gz --right R2_001.fastq.gz --SS_lib_type RF --pairs_together --PARALLEL_STATS --CPU 10
